### ISSUE TITLE
Login of existing user redirect doesn't work

### ISSUE THREAD

**Issue by zArchitectBill** [saadmk11/banking-system#36]
When I login with a registered user, I get an error that /accounts/profile isn't in urls.py. The default behavior of LoginView is to redirect to that URL _unless_  you have LOGIN_REDIRECT_URL set in settings.py. I updated mine to point to /transactions/report and now it works fine (unless the user doesn't have an account, which happens if you try to log in with a superuser account instead of one that has registered with the site)

You might want to update the master branch to include that entry in settings.py

**Comment by saadmk11** [comment]
Thanks for reporting the issue, I will try to update the codebase with the fix, but you are welcome to send a PR :)

**Comment by fredmorgan2k4** [comment]
createsuperuser cannot login. it says page not found. please help me out here

**Comment by SamiMezghani52** [comment]
Hello, I noticed this issue before I could your comments and I had to proceed just like you mentioned with the LIGIN_REDIRECT_URL which is the best way.

**Comment by saadmk11** [comment]
Closed on https://github.com/saadmk11/banking-system/pull/55
